<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>TestSuiteForDataDriverTests</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>3</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>true</rerunImmediately>
   <testSuiteGuid>4e3c2228-92ee-4b5f-b0da-de92a54d7adb</testSuiteGuid>
   <testCaseLink>
      <guid>080b1dec-295f-4478-837f-3028b6630371</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/DataDrivenDemo</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>52f11746-c679-4515-8c13-527466efcf1d</id>
         <iterationEntity>
            <iterationType>ALL</iterationType>
            <value></value>
         </iterationEntity>
         <testDataId>Data Files/LoginData</testDataId>
      </testDataLink>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId>52f11746-c679-4515-8c13-527466efcf1d</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>username</value>
         <variableId>00011686-ddd0-4d77-96dc-2403d126c12b</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>52f11746-c679-4515-8c13-527466efcf1d</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>password</value>
         <variableId>454ef7bd-6b3c-4e18-a8e9-23dbf36e4865</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
